### PR TITLE
Todo review pull request

### PR DESCRIPTION
**Pull request by christianonoh**

### CODE REVIEW

**Comment by mutugi-c** [comment]
JS best practices
Your code is well done, Christian. I really liked your execution of the Task class. However, it has me thinking of modularity or using components that can be easily reused or modified. This approach would make code more maintainable, easier to understand, and less prone to errors.

DRY, KISS & YAGNI
The event listeners in the Task class are easy to understand, but given that most of them are directed towards the [taskContainer](https://github.com/christianonoh/toDoBestPractices/blob/review/src/task.js#:~:text=this.taskContainer.addEventListener(%27click,%7D)%3B), they could be executed differently to avoid repetition and make your code DRY.

HTML & CSS best practices
Your use of CSS is also good. However, it could even be better if you added a few comments and avoided leaving any commented-out code like in this [case](https://github.com/christianonoh/toDoBestPractices/blob/review/src/style.css#:~:text=%23tasks%20%7B,%7D).

**Comment by christianonoh** [comment]
@mutugi-c Thank you for your honest review, I've worked on the recommendations you made. Please kindly review my work and give me some feedback. Thank you 🙏

**Comment by mutugi-c** [comment]
Hello @christianonoh. The event listeners now look good and are easy to follow with the event delegation. The CSS code also looks clean without the commented-out code. 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

**Comment by christianonoh** [comment]
## Thank you for your review 😀

**Pull request merged**
